# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: rouge
markdown: kramdown
disqus: YoungKyonYou
google_analytics: YoungKyonYou
title: MyWay

defaults:
  - scope:
      path: "" # empty string for all files
    values:
      title: MyWay

description: Stylish Jekyll Theme
author:
  name: YoungKyonYou
  email: youngkyon1324@naver.com
  github: /YoungKyonYou
  twitter: young
  pinterest: asd123
  linkedin: asd123
  bio: Integration of Knowledge
  email_md5: youngkyon1324@naer.com

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

# set it as url of an image
# sidebar_background_image: https://www.dropbox.com/s/g9h23zrycedxtk5/sky.png?raw=1

BASE_PATH:

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jemoji
